
[2021-12-04 09:31:39.456078]: Started socket on port 3333
[2021-12-04 09:34:44.464664]: Started socket on port 3333
[2021-12-04 09:35:18.288245]: Connection recieved from ('127.0.0.1', 41452)
[2021-12-04 09:35:24.640836]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 09:35:25.142603]: Reached breakpoint of directory transfer for ('127.0.0.1', 41452)
[2021-12-04 09:35:28.157341]: Breakpoint resolved for ('127.0.0.1', 41452)
[2021-12-04 09:35:28.157945]: Sending specto.py to ('127.0.0.1', 41452)
[2021-12-04 09:35:31.162214]: Sending mood_ai.py to ('127.0.0.1', 41452)
[2021-12-04 09:35:33.165545]: Error: failed to transfer Audio+AI to ('127.0.0.1', 41452)
[2021-12-04 14:00:24.453899]: Started socket on port 3333
[2021-12-04 14:00:32.075008]: Connection recieved from ('127.0.0.1', 60116)
[2021-12-04 14:01:17.165656]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 14:07:38.770424]: Started socket on port 3333
[2021-12-04 14:08:00.180369]: Connection recieved from ('127.0.0.1', 60158)
[2021-12-04 14:08:03.889102]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 14:08:04.390652]: Reached breakpoint of directory transfer for ('127.0.0.1', 60158)
[2021-12-04 14:08:07.407371]: Breakpoint resolved for ('127.0.0.1', 60158)
[2021-12-04 14:08:07.407757]: Sending specto.py to ('127.0.0.1', 60158)
[2021-12-04 14:13:29.626489]: Started socket on port 3333
[2021-12-04 14:13:35.505525]: Connection recieved from ('127.0.0.1', 60184)
[2021-12-04 14:13:41.199816]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 14:15:39.247379]: Started socket on port 3333
[2021-12-04 14:15:46.444966]: Connection recieved from ('127.0.0.1', 60202)
[2021-12-04 14:15:53.313012]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 14:15:53.814547]: Reached breakpoint of directory transfer for ('127.0.0.1', 60202)
[2021-12-04 14:15:56.829532]: Breakpoint resolved for ('127.0.0.1', 60202)
[2021-12-04 14:15:56.829996]: Sending specto.py to ('127.0.0.1', 60202)
[2021-12-04 14:15:59.837165]: Sending mood_ai.py to ('127.0.0.1', 60202)
[2021-12-04 14:16:02.844210]: Sending main.py to ('127.0.0.1', 60202)
[2021-12-04 14:16:05.851781]: Sending audio_analysis.py to ('127.0.0.1', 60202)
[2021-12-04 14:55:12.930488]: Started socket on port 3333
[2021-12-04 14:55:28.840936]: Connection recieved from ('127.0.0.1', 54744)
[2021-12-04 14:55:32.467187]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 14:55:32.968425]: Reached breakpoint of directory transfer for ('127.0.0.1', 54744)
[2021-12-04 14:55:36.020536]: Breakpoint resolved for ('127.0.0.1', 54744)
[2021-12-04 14:55:36.021082]: Sending specto.py to ('127.0.0.1', 54744)
[2021-12-04 14:55:39.027450]: Sending mood_ai.py to ('127.0.0.1', 54744)
[2021-12-04 14:55:42.729977]: Sending main.py to ('127.0.0.1', 54744)
[2021-12-04 14:55:45.736849]: Sending audio_analysis.py to ('127.0.0.1', 54744)
[2021-12-04 14:56:01.327115]: Breaking socket loop, requests made: 2
[2021-12-04 14:56:01.327805]: Connection to ('127.0.0.1', 54744) broken
[2021-12-04 15:04:53.290563]: Started socket on port 3333
[2021-12-04 15:05:02.050500]: Connection recieved from ('127.0.0.1', 54842)
[2021-12-04 15:05:05.682137]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 15:05:06.183449]: Reached breakpoint of directory transfer for ('127.0.0.1', 54842)
[2021-12-04 15:05:14.335119]: Breakpoint resolved for ('127.0.0.1', 54842)
[2021-12-04 15:05:14.335514]: Sending specto.py to ('127.0.0.1', 54842)
[2021-12-04 15:05:17.339383]: Sending mood_ai.py to ('127.0.0.1', 54842)
[2021-12-04 15:05:20.344313]: Sending main.py to ('127.0.0.1', 54842)
[2021-12-04 15:05:23.348393]: Sending audio_analysis.py to ('127.0.0.1', 54842)
[2021-12-04 15:06:48.465552]: Breaking socket loop, requests made: 2
[2021-12-04 15:06:48.466507]: Connection to ('127.0.0.1', 54842) broken
[2021-12-04 15:06:58.698959]: Started socket on port 3333
[2021-12-04 15:07:07.465440]: Connection recieved from ('127.0.0.1', 54894)
[2021-12-04 15:07:11.900979]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 15:07:12.402624]: Reached breakpoint of directory transfer for ('127.0.0.1', 54894)
[2021-12-04 15:07:18.743259]: Breakpoint resolved for ('127.0.0.1', 54894)
[2021-12-04 15:07:18.743685]: Sending specto.py to ('127.0.0.1', 54894)
[2021-12-04 15:07:21.748041]: Sending mood_ai.py to ('127.0.0.1', 54894)
[2021-12-04 15:07:24.751288]: Sending main.py to ('127.0.0.1', 54894)
[2021-12-04 15:07:27.755524]: Sending audio_analysis.py to ('127.0.0.1', 54894)
[2021-12-04 15:08:53.677760]: Breaking socket loop, requests made: 2
[2021-12-04 15:08:53.679253]: Connection to ('127.0.0.1', 54894) broken
[2021-12-04 15:09:07.719229]: Started socket on port 3333
[2021-12-04 15:09:16.745149]: Connection recieved from ('127.0.0.1', 54914)
[2021-12-04 15:09:20.118625]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 15:09:20.620019]: Reached breakpoint of directory transfer for ('127.0.0.1', 54914)
[2021-12-04 15:09:29.218527]: Breakpoint resolved for ('127.0.0.1', 54914)
[2021-12-04 15:09:29.219070]: Sending specto.py to ('127.0.0.1', 54914)
[2021-12-04 15:09:32.223267]: Sending mood_ai.py to ('127.0.0.1', 54914)
[2021-12-04 15:09:35.225853]: Sending main.py to ('127.0.0.1', 54914)
[2021-12-04 15:09:38.228880]: Sending audio_analysis.py to ('127.0.0.1', 54914)
[2021-12-04 15:09:46.963742]: Breaking socket loop, requests made: 2
[2021-12-04 15:09:46.964558]: Connection to ('127.0.0.1', 54914) broken
[2021-12-04 15:11:24.743548]: Started socket on port 3333
[2021-12-04 15:11:33.641407]: Connection recieved from ('127.0.0.1', 54926)
[2021-12-04 15:11:41.180857]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 15:11:41.683228]: Reached breakpoint of directory transfer for ('127.0.0.1', 54926)
[2021-12-04 15:11:43.193745]: Breakpoint resolved for ('127.0.0.1', 54926)
[2021-12-04 15:11:43.194134]: Sending specto.py to ('127.0.0.1', 54926)
[2021-12-04 15:11:46.197459]: Sending mood_ai.py to ('127.0.0.1', 54926)
[2021-12-04 15:11:49.200636]: Sending main.py to ('127.0.0.1', 54926)
[2021-12-04 15:11:52.204844]: Sending audio_analysis.py to ('127.0.0.1', 54926)
[2021-12-04 15:12:49.505935]: Breaking socket loop, requests made: 2
[2021-12-04 15:12:49.506733]: Connection to ('127.0.0.1', 54926) broken
[2021-12-04 15:13:42.298722]: Started socket on port 3333
[2021-12-04 15:13:52.694871]: Connection recieved from ('127.0.0.1', 54928)
[2021-12-04 15:13:59.539611]: ['Audio+AI']-Found directory, sending all files...
[2021-12-04 15:14:00.040968]: Reached breakpoint of directory transfer for ('127.0.0.1', 54928)
[2021-12-04 15:14:03.052164]: Breakpoint resolved for ('127.0.0.1', 54928)
[2021-12-04 15:14:03.052593]: Sending specto.py to ('127.0.0.1', 54928)
[2021-12-04 15:14:06.056933]: Sending mood_ai.py to ('127.0.0.1', 54928)
[2021-12-04 15:14:09.060910]: Sending main.py to ('127.0.0.1', 54928)
[2021-12-04 15:14:12.065405]: Sending audio_analysis.py to ('127.0.0.1', 54928)
[2021-12-04 15:14:34.140799]: Breaking socket loop, requests made: 2
[2021-12-04 15:14:34.141708]: Connection to ('127.0.0.1', 54928) broken
[2021-12-04 16:02:39.001652]: Started socket on port 3333
[2021-12-04 16:02:53.173708]: Connection recieved from ('127.0.0.1', 53966)
[2021-12-04 16:02:56.255246]: ['dir']-Found directory, sending all files...
[2021-12-04 16:02:56.756642]: Reached breakpoint of directory transfer for ('127.0.0.1', 53966)
[2021-12-04 16:02:59.774532]: Breakpoint resolved for ('127.0.0.1', 53966)
[2021-12-04 16:02:59.775121]: Sending two.py to ('127.0.0.1', 53966)
[2021-12-04 16:03:02.782425]: Sending main.py to ('127.0.0.1', 53966)
[2021-12-04 16:03:11.554634]: Breaking socket loop, requests made: 2
[2021-12-04 16:03:11.556024]: Connection to ('127.0.0.1', 53966) broken
[2021-12-04 16:42:22.495384]: Started socket on port 3333